### ISSUE TITLE
Sphere with holes ?

### ISSUE THREAD

**Issue by Charly-Empereur-mot** [m3g/packmol#22]
Dear Leandro,

First, thank you very much for PackMol, it's really a great tool :+1: 

I'm trying to build a vesicle with some holes on its surface, using a 5 beads CG model of lipid POPC. It worked fine until I started testing cylinders. I have obtained a single layer vesicle to begin with, then a double layer vesicle correctly packed, and I could run it in simulation. Then I'm trying to add the outside cylinder restraints, so I can theoretically create holes.

I basically want to add an outside cylinder restraint on X-axis to punch 2 holes of 2-4 nm in the vesicle (for later leaflets equilibration purposes in the double layer vesicle).

Here is what I'm trying, using the inner leaflet as test:

```
nloop 1000          # default 200           /!\ increasing does not change my problem
avoid_overlap yes   # default yes        /!\ yes-no does not change my problem
maxit 20           # default 20                /!\ increasing does not change my problem
discale 0.75       # default 1
movefrac 0.05
sidemax 3000
tolerance 3.0 # default minimal spacing of particles

output vesicle.pdb
filetype pdb

structure POPC.pdb
  number 2000                       /!\ I tried smaller numbers without seeing holes or the algo does not proceed
  resnumbers 3
  #inside cylinder -2000. 0. 0. 1. 0. 0. 200. 4000.   /!\ does not work, while I understood this should represent no additional restraints
  #outside cylinder -2000. 0. 0. 1. 0. 0. 15. 4000.   /!\ this what I would like = 2 holes on the X-axis of approximately 3 nm
  #outside cylinder 0. 0. 0. 1. 0. 0. 10. 2000.         /!\ even this does not work with 500 lipids, while if I comment it works with 2000+ lipids
  atoms 1
    radius 3.63
    inside sphere 0. 0. 0. 123.
  end atoms
  atoms 2
    radius 2.43
  end atoms
  atoms 3 5
    radius 3.08
    outside sphere 0. 0. 0. 124.
  end atoms
  atoms 4
    radius 2.50
  end atoms
end structure
```

If I try to put the origin of the cylinder at 0,0,0 it does not change the problem. In the first commented cylinder try (inside cylinder), I think I'm not adding more restraints as the sphere should fall entirely inside the cylinder I request. I'm really stuck here.

Could you please point what the error is here ?

Also I'm not interested into using exclusion spheres to create the holes in the vesicle, unless I absolutely have to, as it seems less suited for obtaining what I want.

Thank you very much for your advice

**Comment by leandromartinez98** [comment]
Thank you for your feedback. I will ask you some help in figuring out what kind of issue is that by simplifying the problem first. I tested this input, in which I put some water molecules in a sphere with a whole:


`
tolerance 2.0
filetype pdb
output test2.pdb

structure water.pdb 
  number 1000 
  inside sphere 0. 0. 0. 50.
  outside cylinder -60. 0. 0. 1. 0. 0. 20. 120. 
end structure
`

This example seems to have worked as expected: 

<img src="http://leandro.iqm.unicamp.br/arquivos/test1.png">

If you can, please clarify what you mean by "does not work" (what is the output, exactly). Also it would be nice if you could provide all the example files.

I must note, however, that even for this water example Packmol has a little more difficulty in packing everything than I would like, probably because of the intersections of the the shapes. It might be that these difficulties become prohibitive in much more complex systems. We might try to work on that if we find out that that is the sort of problem you are facing. 

Anyway, as a general rule, I suggest that you try your constraints with simple molecules (single atom molecules preferably) first, to see if the geometry is ok.

**Comment by Charly-Empereur-mot** [comment]
Thank you for your prompt answer.

It seems to me it is indeed difficulties in packing. I will try my best to describe the problem while keeping it short, also I attached the PDB file (I believe that's all, right ?): [POPC.zip](https://github.com/m3g/packmol/files/4753021/POPC.zip)

First I validate geometry by adding first 2k lipids in a sphere + 2k lipids in a rectangular box:

```
nloop 1000          # default 200
avoid_overlap yes   # default yes
maxit 20           # default 20
discale 0.75       # default 1
movefrac 0.05
sidemax 3000

tolerance 3.0 # default minimal spacing of particles

output vesicle.pdb
filetype pdb

# SPHERE
structure POPC.pdb
  number 2000
  resnumbers 3
  atoms 1
    radius 3.63
    inside sphere 0. 0. 0. 123.
  end atoms
  atoms 2
    radius 2.43
  end atoms
  atoms 3 5
    radius 3.08
    outside sphere 0. 0. 0. 123.
  end atoms
  atoms 4
    radius 2.50
  end atoms
end structure

# RECTANGULAR BOX
structure POPC.pdb
  number 2000
  resnumbers 3
  inside box -20. -20. -2500. 20. 20. 2500.
  atoms 1
    radius 3.63
  end atoms
  atoms 2
    radius 2.43
  end atoms
  atoms 3 5
    radius 3.08
  end atoms
  atoms 4
    radius 2.50
  end atoms
end structure
```
 And I get these after 60 GENCAN loops (I stop the program manually at this point):

![image](https://user-images.githubusercontent.com/44687951/84163774-24495200-aa72-11ea-8037-b1ff45c66c31.png)
![image](https://user-images.githubusercontent.com/44687951/84163983-53f85a00-aa72-11ea-937a-3c6f02085298.png)

So now I want to use the rectangular box as an exclusion volume, so I do this (with increased maxit and nloop + turning avoid_overlap to no):

```
nloop 10000          # default 200
avoid_overlap no   # default yes
maxit 150           # default 20
discale 0.75       # default 1
movefrac 0.05
sidemax 3000

tolerance 3.0 # default minimal spacing of particles

output vesicle.pdb
filetype pdb

# INNER LAYER

structure POPC.pdb
  number 2000
  resnumbers 3
  outside box -20. -20. -2500. 20. 20. 2500.
  atoms 1
    radius 3.63
    inside sphere 0. 0. 0. 123.
  end atoms
  atoms 2
    radius 2.43
  end atoms
  atoms 3 5
    radius 3.08
    outside sphere 0. 0. 0. 123.
  end atoms
  atoms 4
    radius 2.50
  end atoms
end structure
```

And I get this output:

```
  Fixing bad orientations ...      2 of      3
  Moving worst molecules ... 
  Function value before moving molecules:   12927983027.476059     
  Type         1 molecules with non-zero contributions:   93.80%
  Moving       100 molecules of type         1
  New positions will be based on good molecules (movebadrandom is not set) 
   Moving:|0                                                             100%|
          |******************************************************************|
  Function value after moving molecules:   11925811555.621391     
  Packing:|0                                                             100%|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
          |******************************************************************|
  Fixing bad orientations ...      3 of      3
  Moving worst molecules ... 
  Function value before moving molecules:   11161516013.617447     
  Type         1 molecules with non-zero contributions:   88.80%
  Moving       100 molecules of type         1
  New positions will be based on good molecules (movebadrandom is not set) 
   Moving:|0                                                             100%|
          |******************************************************************|
  Function value after moving molecules:   10232866749.161064     

  Restraint-only function value:    10232866749.161064     
  Maximum violation of the restraints:    9249689.5626439620     
  ERROR: Packmol was unable to put the molecules
         in the desired regions even without
         considering distance tolerances. 
         Probably there is something wrong with
         the constraints, since it seems that
         the molecules cannot satisfy them at
         at all. 
         Please check the spatial constraints and
         try again.
  >The maximum number of cycles (       10000 ) was achieved.
   You may try increasing it with the nloop keyword, as in: nloop 1000
```

**Comment by leandromartinez98** [comment]
I was able to get a solution using this input:

```
nloop 1000          # default 200
nloop0 1000          # default 20
avoid_overlap yes   # default yes
maxit 20           # default 20
discale 3.0       # default 1
sidemax 3000

tolerance 5.0 # default minimal spacing of particles

output vesicle.pdb
filetype pdb

# SPHERE cut by a cylinder
structure POPC.pdb
  number 2000
  resnumbers 3
  outside cylinder -2500. 0. 0. 1. 0. 0. 20. 5000.
  atoms 1
    inside sphere 0. 0. 0. 123.
  end atoms
  atoms 3 5
    outside sphere 0. 0. 0. 123.
  end atoms
end structure
```
In summary, I removed some atom radii definitions (I do not think they make much of a difference there), but increased the overall tolerance to 5.0 and the "discale" option to 3.0. This will push the molecules far from each other at the start and sometimes improves the result. I also increased the number of initial loops with the "nloop0" keyword.

I get a solution after a couple of minutes here, which looks like this:

![image](https://user-images.githubusercontent.com/31046348/84170608-46ca7380-aa50-11ea-9d08-7c4e82e30cd1.png)

I am not sure if that will fit your needs, but probably this example provides some guidance to try some other options in your setup.

**Comment by Charly-Empereur-mot** [comment]
Thank you very much for your guidance, it works flawlessly :+1:
