### ISSUE TITLE
Write CONECT records in output PDB files?

### ISSUE THREAD

**Issue by jchodera** [m3g/packmol#23]
Thanks again for producing such a wonderfully useful tool!

I was wondering if it would be possible to have packmol preserve connectivity information on writing output PDB files. The [PDB Specification](http://www.wwpdb.org/documentation/file-format) requires that nonstandard residues (anything but the standard 20 amino acids, 4 RNA and DNA nucleic acids, and water) use the [`HETATM`](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#HETATM) record and include [`CONECT`](http://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT) records that define connectivity between nonstandard atoms. The reason for this is that there is absolutely no way to infer what the connectivity in the output molecules otherwise. 

Is it possible to add a feature that would preserve the molecular connectivity and write the corresponding `CONECT` records within the output PDB file? Many software packages like [OpenMM](http://openmm.org) require this information in order to be able to use the downstream PDB files.

cc: https://github.com/openmm/openmmforcefields/issues/140

**Comment by lmiq** [comment]
Implemented in version 20.2
