### ISSUE TITLE
packing molecules in a hexagonal unit cell

### ISSUE THREAD

**Issue by goodwilling** [m3g/packmol#24]
Hi. Packmol is a great tool in creating initial configurations.  I am wondering if it can now be used for packing molecules into a hexagonal unit cell. Thank you very much.

**Comment by lmiq** [comment]
No, no directly. We are hoping to release a new improved version of Packmol until the end of the year with that and other improvements. Currently one would have to build a cubic box and cut it with an external tool to make it hexagonal.

**Comment by pfebrer** [comment]
Hi! I discovered your code today and it was a very nice surprise!

However I also need to constrain the coordinates to a non-orthogonal cell. I haven't found anything in the documentation, is the implementation you mentioned here already in the code? Thanks!

**Comment by lmiq** [comment]
No, it is not. It will actually be a complete rewrite of the code, with new features. The [most important core part](https://github.com/m3g/CellListMap.jl) is written already and supports general PBCs, but I still need to write the actual interface. Maybe for the end of the year, but I cannot guarantee that.
