### ISSUE TITLE
problem opening file with full path in MacOS and server

### ISSUE THREAD

**Issue by lmiq** [m3g/packmol#25]
Just for clarity:

structure /Users/Nemo/RESP/Octocrylene/octocrylene.pdb

leads to

Fortran runtime error: Cannot open file '/Users/Nemo/RESP/Octocrylene/octocrylene.': No such file or directory

Somehow, when specifying the path, the extensions gets dropped while it works if placing the pdb file in the same directory as the script and run without path.

I have tried this on macOS, though that might be some macOS specific security setting where I’d need to grant access to some folder.

The strange thing to me was that I observed the same behaviour on centOS. However, that system is a shared resources server so it may be some other problem with permissions.

**Comment by rkingsbury** [comment]
I'm not sure if this is related, but I've also observed some shortcomings with how packmol processes paths: #27
