### ISSUE TITLE
Errors with long filename/path 

### ISSUE THREAD

**Issue by taidbui** [m3g/packmol#29]
I have encountered an errors when I use quite a long path to my pdb files to build the system with packmol. Please find below the error:
`At line 407 of file output.f90 (unit = 15)
Fortran runtime error: Cannot open file '/Users/tb/Library/CloudStorage/OneDrive-tb/MD/models/oplsaa/C26H32O_GROMOS_ATB_B': No such file or directory`

As you can see, the filename is not complete because it is longer than the one shown in the error above. When I shortened my file name, it worked just fine. I wonder if it is possible to increase the character limit for the input path.

Thank you!

**Comment by lmiq** [comment]
Which version are you using? That should be solved in the latest versions.

**Comment by taidbui** [comment]
I see. Thank you very much. I installed via conda, and the latest version is 20.01.

**Comment by lmiq** [comment]
That was fixed on version 20.2.3.
