### ISSUE TITLE
packmol dependence on libgfortran3?

### ISSUE THREAD

**Issue by pmqn** [m3g/packmol#32]
It seems packmol depends on package libgfortran3.
However, on newer ubuntu OS, libgfortran3 is no long supported as it requires an older version of gcc.
Running packmol will lead to this error
`error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory`

**Comment by mattwthompson** [comment]
Hi, could you share how you installed it (or built from source)?

**Comment by pmqn** [comment]
> Hi, could you share how you installed it (or built from source)?

I followed the instruction to install packmol
```
tar -xvzf packmol.tar.gz
cd packmol
make
```
I am working on Ubuntu 22.04.1 LTS and have difficulty in installing libgfortran3

**Comment by lmiq** [comment]
This looks like a broken installation of gfortran. Normally you would need to install this library separately.

**Comment by lmiq** [comment]
usually you should just have done "sudo apt install gfortran" and it should work.

**Comment by lmiq** [comment]
Did you succeed? Can you provide any additional info on the problem?

**Comment by pmqn** [comment]
I reinstalled all and now it works perfectly. Thanks a lot!
