### ISSUE TITLE
PDB handling issue 

### ISSUE THREAD

**Issue by Kr0n0ss** [m3g/packmol#35]
Hi,
Many thanks for such a nice tool. 
I have a small problem. When packing my system I use the keyword add_amber_ter and it effectively add the TER keyword where it should, however in a second step to solvate the previous created pdb file (which I now load in packmol as a single molecule), packmol removes the TER keyword from the original pdb file. It only adds TER for the ions and waters. Seems that packmol doesn't simply take my previous pdb file but does some handling where it misses to kep the TER. 
Any suggestions on how to fix this?
Thanks in advance!

**Comment by lmiq** [comment]
Thanks for noticing that, indeed Packmol only preserves the lines of the original PDB atom containing the coordinates. I will try to work around that asap. At this moment I don't have an easy solution, one would need to write a custom script to do that.

**Comment by lmiq** [comment]
I've added now (version 20.4.0) an option called `amber_ter_preserve`.  Add it to your input file, and it should work. Please check it for me and let me know if it is working as expected.

**Comment by Kr0n0ss** [comment]
amber_ter_preserve did the trick. Many thanks!!!

**Comment by lmiq** [comment]
Closed with v20.4.0
