### ISSUE TITLE
Packing, Saving intermediate PDB files 

### ISSUE THREAD

**Issue by stippner** [m3g/packmol#40]
Hello, 

thank you very much for providing such a nice and intuitive tool. 
Right now I want to pack multiple molecules strands into one big cube. For that I am  interested in dumping intermediate files during the packing process in order to understand better how the actual packing is performed. 
Is there any way to do that? 

Best regards,
Simon

**Comment by lmiq** [comment]
You can use this option:

Write the current point to output file even if it is worse than the the best point so far (used for checking purposes only):
Usage: writebad 

to write all structures obtained, after each optimization loop.

Another feature that might be useful is this one:

http://leandro.iqm.unicamp.br/m3g/packmol/userguide.shtml#restart
