### ISSUE TITLE
<< Web page not working >>

### ISSUE THREAD

**Issue by icamps** [m3g/packmol#47]
Dear @m3g ,

Could be possible to duplicate (on other server) the web page with the instruction about how to use PACKMOL? The pages at UNICAMP server are not working (at least from my ISP or either using 3/4G mobile network).

Thanks in advance.

Camps

**Comment by lmiq** [comment]
Yes, the page is down. Seems to be an issue with the university as server, thus probably it will be back soon. But hosting it on GitHub is on my plans.

**Comment by saffari101** [comment]
same here, webpage does not work.

**Comment by m3g** [comment]
The original server is working now.

Additionally, the site is now cloned here: https://m3g.github.io/packmol/

Probably that one will become the only site at some point. I won't close this issue so the reference to the new site is kept for if someone reaches this issue by another server crash. I will be closed when the original server is deprecated.

**Comment by lmiq** [comment]
Now the page has been definitely moved to github, and there is where it will be maintained. Therefore, we will probably have less maintenance issues from now on.
