### ISSUE TITLE
Removes existing TER records from AMBER formatted lipid pdb

### ISSUE THREAD

**Issue by fr-0zt** [m3g/packmol#51]
V20. removes existing TER records from the input PDB files. _preserve_amber_ter_ is not valid now. If I use _add_amber_ter_ it will only add TER records to new molecules created not the exiting structures. This is a problem because when creating a solvated lipid bilayer with different solvent molecules compatible with AMBER.

**Comment by lmiq** [comment]
Can you provide some input file example so I can test that more easily?

**Comment by fr-0zt** [comment]
[packmol-input.zip](https://github.com/m3g/packmol/files/11647856/packmol-input.zip)

I have attached my script and inputs for the model. Because preserve_amber_ter does not work, I wrote a separate awk script to add later on.

**Comment by lmiq** [comment]
Which version exactly are you using? It seems that in `20.14.2` which is the latest one, those options are working.

At least, using the following input file: 

```
# packmol_input.inp

add_amber_ter
amber_ter_preserve

# Packmol input file for generating an assembly with lipid bilayer and ionic liquid

# Tolerance for overlapping atoms during packing
tolerance 2.2

# File type for input and output files
filetype pdb

# Output file name for the generated assembly
output assembly-bilayer-choline-glycolate.pdb

# Random seed for reproducibility (-1 for random seed)
seed -1

# Maximum number of attempts for each placement
nloop0 10000

# Ionic liquid molecules below the lipids

# Cation structure file and placement information
structure ../Mol_red1-out.ent
  number 1332
  inside box 0.0 0.0 0.0 110.0 110.0 70.0
end structure

# Anion structure file and placement information
structure ../Mol_red2-out.ent
  number 1332
  inside box 0.0 0.0 0.0 110.0 110.0 70.0
end structure

# Lipid bilayer structure

# Lipid bilayer structure file and placement information
structure ../step5_assembly-amber-converted-wout-water.pdb
  number 1
  inside box 0.0 0.0 70.0 110.0 110.0 120.0
end structure

# Ionic liquid molecules over the lipids

# Cation structure file and placement information
structure ../Mol_red1-out.ent
  number 1332
  inside box 0.0 0.0 120.0 110.0 110.0 190.0
end structure

# Anion structure file and placement information
structure ../Mol_red2-out.ent
  number 1332
  inside box 0.0 0.0 120.0 110.0 110.0 190.0
end structure
```

I got the correct behavior (added `TER` in between molecules of the solvents and preserved the `TER` flags of the `step5...` structure).

**Comment by lmiq** [comment]
The `amber_ter_preserve` option was specifically added in version `20.14.0`, so if you are using a version older than that one, you won't get the expected behavior, for sure.
