### ISSUE TITLE
<< Filling atom ring from the center >>

### ISSUE THREAD

**Issue by icamps** [m3g/packmol#55]
Hello,

I am trying to add water molecules to a nanoring made of Si.

When using 300 water molecules, they are always distributed outside the ring. Only when I add 500, will there be water molecules inside the ring.

How can I force PACKMOL to always start adding water molecules from the center or inside the nanoring?

Regards,

Camps

**Comment by lmiq** [comment]
You have to add some constraint to the water molecules such that the are in the region you want. Without further information, I would guess that you need a `inside cylinder` constraint (see constraints of type 9 in https://m3g.github.io/packmol/userguide.shtml).

**Comment by icamps** [comment]
As my system is a ring, won't the sphere be the better constraint thinking in 3D distribution?

**Comment by lmiq** [comment]
I don't know... That depends on what you need.
