### ISSUE TITLE
"FORCED" output overwrites standard output

### ISSUE THREAD

**Issue by SSchott** [m3g/packmol#56]
Hi Leandro,

Noticed some of my packings have been failing lately, and that the FORCED output seemed to be missing. At some point, it seems like the forced output file name was renamed `xyzout_forced`, but this is not used by the output function (see https://github.com/m3g/packmol/blob/42c8805c160cfe78ab6819e44f66fe40f5cb3bc1/src/checkpoint.f90#L84C51-L84C51). 

In my own code I just replaced `xyzout_forced` with `xyzout` and removed the definition in the header, but I am hesitant to just pass a pull request, as I guess there was an intention in the implementation of the variable name?

**Comment by lmiq** [comment]
Thanks for reporting. I'm fixing it now and the fix will be available in the 20.14.3 version.

**Comment by lmiq** [comment]
Should be ready now, and fixed in 20.14.3. Let me know if you continue to experience the issue.
