### ISSUE TITLE
Co-solvent MD with Packmol

### ISSUE THREAD

**Issue by H-EKE** [m3g/packmol#58]
Hi,

I am trying to set-up a system for MD simulation, where I have the protein, water, ions and benzene. I would like to ensure a concnetration of 0.1M of benzene, but I am not sure which is the best way to proceed. Is this the correct way to ensure that concentration? Herewith the input file that im using:

```
tolerance 2.0
filetype pdb
output solvated.pdb

structure conformation.pdb
  number 1
  center
  fixed 0. 0. 0. 0. 0. 0.
end structure

structure WATER.pdb
  number   20920
  inside box -43.3475 -44.8825 -42.614 43.3475 44.8825 42.614
end structure


structure SODIUM.pdb
  number       60
  inside box -43.3475 -44.8825 -42.614 43.3475 44.8825 42.614
end structure
  

structure CHLORIDE.pdb
  number 54
  inside box -43.3475 -44.8825 -42.614 43.3475 44.8825 42.614
end structure

structure benzene.pdb
  number 2092   
  inside box -43.3475 -44.8825 -42.614 43.3475 44.8825 42.614
end structure
```

**Comment by lmiq** [comment]
Your input file seems fine, but probably the concentration is wrong as 0.01M seems "Mol per liter", and you have put 0.01 fraction of benzene molecules relative to water molecules, which is not the same.
