### ISSUE TITLE
Conda-installable?

### ISSUE THREAD

**Issue by davidlmobley** [m3g/packmol#6]
Any chance you could make packmol be conda-installable, such as via a channel on Anaconda.org, or via conda-forge? (The latter would be even better I think).

Thanks!

**Comment by leandromartinez98** [comment]
Dear David, I had never heard about that before. I looked briefly on what it is, and I suppose it is possible to do that, but at this moment I won't be able to do it. Anyway, if someone is already familiar with that and wants to package it, I can totally provide the necessary support from the developer side.

**Comment by davidlmobley** [comment]
Let me clarify a bit more on this. I'll answer your question from #8 directly, but first some background. Please note there are two parts to the background, one being where we are now, and the other being where we are going.

Basically, Anaconda python is a great Python distribution which includes a lot of standard Python packages for science, but ALSO includes `conda`, basically a package manager that handles Python AND non-python dependencies. If you have something which is set up for this package manager and has dependencies which are ALSO set up for the package manager, installing it AND all of its dependencies becomes as simple as `conda install [packagename]` OR if it is not available in the standard packages, `conda install -c [channelname] [packagename]` where the channel is something a "maintainer" makes available that can include various packages. 

Setting these channels up basically just means you make a "build" or builds of your package and push it /them to Anaconda.org in your account or channel. A bunch of has had an `omnia` channel which included our core packages and a bunch of dependencies, so it allowed us to install basically everything we needed. So this gets to your question:

> Thank you David. One question: I see there that you install packmol "via omnia channel on conda". The other issue open for Packmol is that of someone asking if I could make packmol installable through "conda".

Basically, we put a then-current version of Packmol into our Omnia channel. However, it does NOT stay updated, and requires a human to do something to update it (see https://github.com/omnia-md/conda-recipes/issues/744 -- we're looking for someone to update it/maintain). 

This might sound like it's a difficult task, but really it shouldn't be that bad. We use an automatic system to make these builds, so really it's basically as simple as keeping the files in this directory updated: https://github.com/omnia-md/conda-recipes/tree/master/packmol . (In this case, since you moved to GitHub since we did this, we'd want to transition to pulling down your repo from GitHub rather than using the older version from your website. If you decide you're interested in helping with that we can give you an example...) 

That's not quite the end of the story, though, as the "conda channel" approach has some limitations as described here: http://www.omnia.md/blog/2017/5/18/omnias-conda-distribution-now-linked-with-conda-forge -- basically, that the "channel" approach means that people end up with multiple different builds of the same package in different channels, which is a big pain to maintain. So the long-term plan is to migrate to `conda-forge` which would provide common, community-wide builds of all packages we rely on.

So to get back to your question:
> Does that mean that you have already done that? Does it keep the package updated? Can that be shared, such that I can solve the other issue?

*We DO already have `packmol` conda-installable in omnia, though there are two problems:*
1) Even the version we have is out of date and needs someone who can maintain it
2) The better, long-term solution is for it to be in conda-forge, where it would also need someone who can maintain it

If you don't end up getting interested in this, it seems likely I or someone in my group (or @nividic at OpenEye) will get around to it eventually, as we ARE using the tool quite a bit. I just asked you about it as I hoped we might be able to interest you as the developer since then we wouldn't have to serve as middlemen.

**Comment by leandromartinez98** [comment]
Dear David. I realize now that you were the one asking for this feature before :-). Thank you for the explanations. Just to clarify, the version that you download from the site (the "old" site, pre-github) is and will always be the latest github release, so in that concern the software will be up to date if you use your script to fetch it. I might be interested and can provide all the support needed for that, but I am quite overwhelmed with all that information and it is not clear to me what to do, since I am not a user of conda myself.

**Comment by kyleabeauchamp** [comment]
@davidlmobley it looks like our colleague @bgruening has created a conda-forge recipe for packmol:

https://anaconda.org/conda-forge/packmol

https://github.com/conda-forge/packmol-feedstock

Please feel free to sign up someone from your team as a maintainer.

**Comment by rkingsbury** [comment]
It's great to have packmol available via conda-forge. I just wanted to note that the version number of the current latest build is inaccurate. conda reports `v20.010` but the real version is `20.3.1` (which you see when you run the binary). This is a little problematic for code that depends on semantic versioning for checking compatibility (for example, if I want to verify that I have >= 20.3 to ensure support for paths with spaces). 

Hopefully this can be solved in the next released. Thanks!

**Comment by mattwthompson** [comment]
@rkingsbury could you also post this to https://github.com/conda-forge/packmol-feedstock/issues? That's likely where it could get fixed.

As a side note, we (and many others) have been using the conda build for a while now, so this can probably be considered complete & closed 👍

**Comment by rkingsbury** [comment]
> @rkingsbury could you also post this to https://github.com/conda-forge/packmol-feedstock/issues? That's likely where it could get fixed.

Sure, no problem.

> As a side note, we (and many others) have been using the conda build for a while now, so this can probably be considered complete & closed 👍

Agreed!
