### ISSUE TITLE
Creating system with receptor + ligand and water as solvent mix... Duplicate atom serial & max # bonds exceeded errors

### ISSUE THREAD

**Issue by ONISniperOne** [m3g/packmol#60]
Hello,

I'm trying to surround a receptor with solvent mix of ligand + water in 10:1 ratio (no ligand in binding site). When I open the resulting pdb with saved CONECT records in VMD and ChimeraX, I get max # of bonds exceeded and duplicate atom serial, respectively. The original ligand and receptor files have their own CONECT records.

ChimeraX
![image](https://github.com/m3g/packmol/assets/128614019/b1888104-dfd0-40ca-a3c6-0007fc2876db)

VMD
![image](https://github.com/m3g/packmol/assets/128614019/c9e83439-79c2-4ea9-954a-f9fdf40161f4)

Included in the zip file is my receptor, ligand, water, and input file. Thank you!
[PackMol 10.189.zip](https://github.com/m3g/packmol/files/14910732/PackMol.10.189.zip)

**Comment by lmiq** [comment]
Did Packmol ended with the "Success!" message in the case where you see the problem? If not, probably the system is too dense indeed.

If you want to study in details the interactions of these solvents with the protein, checkout our package: https://m3g.github.io/ComplexMixtures.jl
