### ISSUE TITLE
Successful packing - Chimera/ChimeraX bad PDB record

### ISSUE THREAD

**Issue by ONISniperOne** [m3g/packmol#64]
![image](https://github.com/m3g/packmol/assets/128614019/efa2baa4-aea4-45ba-a95f-95240a1c5c8d)

![image](https://github.com/m3g/packmol/assets/128614019/c4d196be-2b68-45a7-8fe6-75df1bfbbb36)

Seems like everything worked, but opening the output pdb in Chimera yields bad record

Seems to be no problem in VMD.
![image](https://github.com/m3g/packmol/assets/128614019/81928725-2414-47b7-bd58-4fb73744ffb2)

I think Chimera and VMD has different serialization scheme at the higher numbers. Any solutions?

**Comment by lmiq** [comment]
If the file opens correctly in VMD, you can try saving it from VMD in another format.

**Comment by lmiq** [comment]
VMD ignores the atom number from the PDB, thus why it does not complain.

**Comment by ONISniperOne** [comment]
Maybe I can try to resave as pdb? Should that fix the #ing issue to open in Chimera?

**Comment by ONISniperOne** [comment]
Update (workaround):

Opened in VMD and saved as .cif as suggested above. Opened the .cif in Chimera/ChimeraX and resaved as pdb file. The bad CONECT record and duplicate serial #ing is fixed. However, some residues can no longer be identified due to the conversion such as CYX (disulfide bonded version of CYS), HIE, and HID. I opened the protein/receptor pdb file used in packmol and the converted system, matchmake the receptor pdb onto the converted, and replaced the protein in the converted system with the one from receptor only pdb from packmol.

**Comment by lmiq** [comment]
The PDB format is not ideal for dealing with very large structures, and it is only useful in MD simulations because the packages ignore the indexing. Probably that should be done by Chimera as well. 

I'm closing the issue, if you have any other question, let me know.
