### ISSUE TITLE
Using atom radii property to tailor parts of molecules that can overlap

### ISSUE THREAD

**Issue by tfhughes** [m3g/packmol#66]
I have a quick question about how atomic radii work. I have a situation where I need to pack to a relatively large density. I don't mind if some atoms overlap but it is critical that others don't. It seems that I ought to be able to set the atom radii to be small for one set of atoms and large for the other set in order to satisfy this type of restraint. Does that sound reasonable?

**Comment by lmiq** [comment]
Yes, that can be used. You can also use 2 radii for some atoms, to make their overlap even less likely at short distances.
See:

https://m3g.github.io/packmol/userguide.shtml#fscale

**Comment by tfhughes** [comment]
Thank you for the reply. Just in case it is related I am using version 20.11.0. Suppose I have the following with only one type of structure:

atoms 1
radius 5
fscale 3
end atoms

My understanding is that when atom 1 from structure A and atom 1 from structure B are greater than 10 Angstrom apart that the distance penalty is 0. And when they are less than 10 Angstrom a penalty with the default shape but scaled by a factor of 3 is applied. Correct?

Also does fscale apply only to the atom-atom distance penalty or does it also apply to the box, plane, etc. restraints as well? Also what is the difference between using radius and fscale as above versus using short_radius and short_radius_scale?

**Comment by lmiq** [comment]
First, I recommend upgrading to 20.14.4 to guarantee that all the options of the manual exist.

> My understanding is that when atom 1 from structure A and atom 1 from structure B are greater than 10 Angstrom apart that the distance penalty is 0. And when they are less than 10 Angstrom a penalty with the default shape but scaled by a factor of 3 is applied. Correct?

Yes correct.

> Also does fscale apply only to the atom-atom distance penalty

Yes, only to the atom-atom distance. 

> Also what is the difference between using radius and fscale as above versus using short_radius and short_radius_scale?

radius and fscale apply to the standard atom-atom penalty function. When you use the "short"  options, you are adding an additional penalty to atom-atom distances, acting at shorter distances (defined by the `short_radius` parameter). And this additional penalty has its own scaling. This is what is illustrated in the figure of the manual here: https://m3g.github.io/packmol/userguide.shtml#fscale

A discussion on why and how this additional constraint was implemented is in this paper: https://pubs.acs.org/doi/full/10.1021/acs.jcim.0c01205  in section "Solving the Protein–Membrane Packing Problem with PACKMOL". It was found that these options were important when packing coarse-grained systems.

**Comment by tfhughes** [comment]
Thank you for your help on this.
