### ISSUE TITLE
Oblong protein > create box dimensions similar to Amber's TIP3PBox iso command?

### ISSUE THREAD

**Issue by ONISniperOne** [m3g/packmol#67]
I have an oblong protein, that's tilted in space. I know I can specify a rectangular box to use by doing

inside box xi. yi. zi. xf. yf. Zf.

But how do I do that in relation to the protein?

**Comment by lmiq** [comment]
You can set the position of the center of mass of the protein with the `fixed` keyword.

**Comment by ONISniperOne** [comment]
But how do I get the edge of the resulting box parallel to the long axis of the protein?

**Comment by lmiq** [comment]
The `fixed` keyword has options to rotate the protein and then you can orient it as you want. Alternatively put the protein in a smaller box inside the larger solvent box.

**Comment by ONISniperOne** [comment]
Also, are the units of xyz in Angstroms?

**Comment by lmiq** [comment]
Yes, exactly. I'll fix it.

The units are the units you have provided in the coordinate file. The package is not sensible to any kind of units. Just be consistent concerning the coordinates, tolerances, and other dimensions.

**Comment by ONISniperOne** [comment]
I'm using a pdb file of a crystal structure, so I guess it's in Angstroms... Thanks!
