### ISSUE TITLE
regression in packmol-memgen 2024.2.9

### ISSUE THREAD

**Issue by xiki-tempula** [m3g/packmol#68]
I have a system where I could use packmol to pack using the packmol bundled in ambertools 23.3 (packmol-memgen=2023.2.24) but not with the packmol bundled in ambertools 23.6 (packmol-memgen=2024.2.9)

Here is how to reproduce the regression.

```
conda create -n ambertools23.3 -c conda-forge ambertools=23.3
conda activate ambertools23.3
packmol < packmol.inp
```
Runs fine

```
conda create -n ambertools23.6 -c conda-forge ambertools=23.6
conda activate ambertools23.6
packmol < packmol.inp
```
Gives 
```
  ENDED WITHOUT PERFECT PACKING: 
  The output file:

    bilayer_system.pdb

  contains the best solution found. 

  Very likely, if the input data was correct, 
  it is a reasonable starting configuration.
  Check commentaries above for more details. 
```
[Archive.zip](https://github.com/m3g/packmol/files/15245741/Archive.zip)

**Comment by lmiq** [comment]
Are the "packmol.inp" files identical?

**Comment by xiki-tempula** [comment]
They are identical. I just realised that they give the same result. It is just that the old one return exit code 0 despite the "ENDED WITHOUT PERFECT PACKING" message, while the new one returns an exit code 137.

**Comment by lmiq** [comment]
Oh, ok. So the new one is the correct one. The proper exit codes were added in newer versions. Probably the solution obtained is good enough, if people where using it in packmol-memgen (I'm not the author nor maintainer of that, so I cannot say much about its choices). How to handle these situations should be something to be chosen in that package.

**Comment by xiki-tempula** [comment]
Thanks for the explanation.
