### ISSUE TITLE
Packmol Version 20.11.0 segfaults on Linux but not on Mac

### ISSUE THREAD

**Issue by tfhughes** [m3g/packmol#70]
Please find the attached tarball containing an input deck and two output log files, one for Mac which runs and one for Linux which fails with a segfault. Is there something wrong with my input file tfh.inp? Is there a way around this segfault?

[packmol.tar.gz](https://github.com/m3g/packmol/files/15378729/packmol.tar.gz)

**Comment by lmiq** [comment]
I can't reproduce the bug, either on 2.11.0 or 2.14.4 (the latest one). Can you reproduce it with 2.14.4?

**Comment by tfhughes** [comment]
I only tried with 20.11.0 on CentOS Linux release 7.9.2009 (Core) where I confirm it is an issue. If I break the long list of atom indices into multiple different blocks in batches of 5 it fixes the issue. In fact running consecutively batches of 1, 2, 5, 10, 20, ..., 50 I can see that all work except 50 for example. Anyway it is no longer an issue for me so feel free to close the case.
