### ISSUE TITLE
Issue "CONECT line"

### ISSUE THREAD

**Issue by fmentink** [m3g/packmol#78]
First thank you for Packmol! Such a great software.
I've been running into an issue using v 20.15.1 On the a previously working pdb I now have an error 
 "Reading coordinate file: GLC.pdb
  ERROR: Could not read any connection index from CONECT line: 
 CONECT    1
 STOP 171"

I'm providing the input file and the pdb file. I am not sure it's a bug but since it was working with previous packmol version (prior to july 12), this might be.

Thanks!

InputFile

# All atoms from diferent molecules will be at least 2.0 Angstroms apart
tolerance 2

# The type of the files will be pdb
filetype pdb

# The name of the output file
output system.pdb

# add first type of solvent molecules
structure GLC.pdb
  number 690
  inside cube 0. 0. 0. 54.9
end structure

pdb file:

COMPND    UNNAMED
AUTHOR    GENERATED BY OPEN BABEL 2.3.2
HETATM    1  C   GLC     1      -1.089   3.717  -0.149  1.00  0.00           C  
HETATM    2  C   GLC     1      -0.607   2.256  -0.112  1.00  0.00           C  
HETATM    3  H   GLC     1      -2.190   3.714  -0.228  1.00  0.00           H  
HETATM    4  H   GLC     1      -0.686   4.220  -1.042  1.00  0.00           H  
HETATM    5  O   GLC     1      -0.648   4.489   0.977  1.00  0.00           O  
HETATM    6  C   GLC     1       0.914   2.160  -0.217  1.00  0.00           C  
HETATM    7  O   GLC     1       1.428   0.835  -0.012  1.00  0.00           O  
HETATM    8  O   GLC     1      -1.276   1.492  -1.132  1.00  0.00           O  
HETATM    9  H   GLC     1      -0.931   1.805   0.842  1.00  0.00           H  
HETATM   10  H   GLC     1      -1.093   4.135   1.768  1.00  0.00           H  
HETATM   11  H   GLC     1      -0.940   1.798  -1.996  1.00  0.00           H  
HETATM   12  H   GLC     1       1.277   0.604   0.923  1.00  0.00           H  
HETATM   13  H   GLC     1       1.366   2.875   0.492  1.00  0.00           H  
HETATM   14  H   GLC     1       1.224   2.450  -1.235  1.00  0.00           H  
CONECT    1    4    3    2    5                                       
CONECT    1                                                           
CONECT    2    8    6    1    9                                       
CONECT    2                                                           
CONECT    3    1                                                      
CONECT    4    1                                                      
CONECT    5    1   10                                                 
CONECT    6   14    2    7   13                                       
CONECT    6                                                           
CONECT    7    6   12                                                 
CONECT    8   11    2                                                 
CONECT    9    2                                                      
CONECT   10    5                                                      
CONECT   11    8                                                      
CONECT   12    7                                                      
CONECT   13    6                                                      
CONECT   14    6                                                      
MASTER        0    0    0    0    0    0    0    0   14    0   14    0
END

**Comment by fmentink** [comment]
Thank you for the quick feedback. 
Actually that did work see attached screenshot
![Screenshot from 2024-11-01 14-07-56](https://github.com/user-attachments/assets/2e8594a5-948a-4fee-ab70-3a09b0f1af31)

**Comment by lmiq** [comment]
Well, at least for a +1 year old version it didn't work. But do you need the connectivity? It just seems to me that those entries are wrong, or what should they mean? 

(you can just delete the `CONECT` lines and then Packmol will run)

**Comment by fmentink** [comment]
May be I was not using an up to date version for a while, hence I was not sure if I should report.
But thanks a lot problem solved!

**Comment by lmiq** [comment]
Actually it depends. If a line with `CONECT` having a single integer number makes sense, packmol should support it. But as far as I understand, it doesn't, so the error message is safer.

**Comment by lmiq** [comment]
Ah, ok. The reading of `CONECT` fields was introduced in 20.1.0. Previously these lines were ignored.

Anyway, if you think that Packmol *should* support these `CONECT` lines with a single number, please let me know the rationale, and I can implement that. 

For now I'm closing the issue. Feel free to open it again if you think so.
