### ISSUE TITLE
Issue with the PBC when lower boundaries are set

### ISSUE THREAD

**Issue by heiariilouchao** [m3g/packmol#79]
Hello,

I'm having an issue with the application of PBCs when the lower boundaries set.

## Problem

Here's the content of my input script:

```Packmol
# Content of build.inp
tolerance 2.5
output tmp.xyz
filetype xyz
pbc 0.2257518699 27.2533888699 0.2121010274 29.2346999726 0.0 140.0

structure sodium.xyz
    number 16
end structure
```
When I launch Packmol with this script using `packmol < build.inp`, the program exits with error code 127. I piped its output to 
[error.log](https://github.com/user-attachments/files/17813047/error.log).

## Workaround

After trying with/without constraints with no improvement, I tried removing the lower boundaries of the PBC:

```Packmol
# pbc 0.2257518699 27.2533888699 0.2121010274 29.2346999726 0.0 140.0
pbc 27.2533888699 29.2346999726 140.0
```

And now it works (see [success.log](https://github.com/user-attachments/files/17813156/success.log)).
With this workaround I'll be able to do what I initially needed by offsetting the further fixed structures accordingly.

## Insights

First, I assume it is a PBC related issue because the system:

- 1. has no constraint except for the implicit ones set by the PBCs application.
- 2. is very simple (see then content of [sodium.xyz](#additional-informations))

I saw in [error.log](https://github.com/user-attachments/files/17813047/error.log) at the `PBC Reference box` line that the lower and higher boundaries have the same values in the x-direction.  
While in [success.log](https://github.com/user-attachments/files/17813156/success.log) they don't.

I don't know the details of the implementation, but maybe it's a parsing error. It seems like Packmol is taking the higher boundary value and assigning it to both the lower and higher boundaries. And this only happened for the x-direction too.

Thank you for your work.

---
## Additional informations

- Packmol version: 20.15.2
- Built from source
- `./configure` gave gfortran

```xyz
# Content of sodium.xyz
1
Sodium
Na	0.00000000	0.00000000	0.00000000
```

**Comment by lmiq** [comment]
The issue there is that the first three coordinates define the lower bound, and the later three the upper bound, such that in your case the box is ill defined in the y-direction. 

I added a new error message that will inform properly the user about that, which will be released in 20.15.3.

Thank you for your feedback.
